/**
 * Pure content + subject builders for the notification rollup email.
 *
 * Deliberately free of database, React and email concerns so the whole
 * thing is unit testable and so the window constants have exactly one home.
 *
 * Copy is generated by renderSummary/resolveHref, the SAME functions the
 * notification bell and inbox use. That is the point: email copy and bell
 * copy cannot drift, and a future ActivityKind gets email copy the moment
 * it gets bell copy.
 */
import { renderSummary, resolveHref } from '@/lib/notification-copy'
import type { MentionInboxRow } from '@/components/activity/types'

/**
 * Rollup debounce. A mention becomes eligible for email only once it is
 * this old, which is what turns a burst of bell events into one email.
 */
export const ROLLUP_WINDOW_MS = 5 * 60 * 1000

/**
 * Maximum age. This is load bearing TWICE, so do not "simplify" it away:
 *
 *  1. Without it, the first deploy would sweep every unread mention in the
 *     app's history and send everyone a wall of email about old events.
 *  2. It is the give up rule. A permanently undeliverable address leaves its
 *     mentions unstamped and they would otherwise be retried on every tap
 *     forever; after a day they age out of the window on their own.
 */
export const ROLLUP_MAX_AGE_MS = 24 * 60 * 60 * 1000

/**
 * Kinds that already have their own purpose built email, so including them
 * here would double send. RelayHandoffEmail covers the two batch moves and
 * ReviewSubmittedDigestEmail covers the client review submission. The bell
 * still fires for all three exactly as before.
 */
export const EXCLUDED_ROLLUP_KINDS: readonly string[] = [
  'batch_passed',
  'batch_sent_back',
  'review_session_submitted',
]

export interface RollupItem {
  summary: string
  href: string
  createdAt: Date
}

export interface RollupClientGroup {
  clientId: string
  clientName: string
  items: RollupItem[]
}

export interface RollupEmailContent {
  groups: RollupClientGroup[]
  totalCount: number
  clientCount: number
}

/**
 * renderSummary prefixes every line with "ClientName · ". The email groups
 * by client and prints the name as a heading, so the prefix is repeated
 * noise on each line. Strip it when present, leave the line alone otherwise.
 */
function stripClientPrefix(summary: string, clientName: string): string {
  const prefix = `${clientName} · `
  return summary.startsWith(prefix) ? summary.slice(prefix.length) : summary
}

export function buildRollupContent(
  rows: MentionInboxRow[],
  baseUrl: string,
): RollupEmailContent {
  const byClient = new Map<string, RollupClientGroup>()

  for (const r of rows) {
    const clientName = r.client.name
    const item: RollupItem = {
      summary: stripClientPrefix(renderSummary(r), clientName),
      href: `${baseUrl}${resolveHref(r)}`,
      createdAt: r.event.createdAt,
    }
    const existing = byClient.get(r.client.id)
    if (existing) {
      existing.items.push(item)
    } else {
      byClient.set(r.client.id, { clientId: r.client.id, clientName, items: [item] })
    }
  }

  const groups = [...byClient.values()].sort((a, b) =>
    a.clientName.localeCompare(b.clientName),
  )
  for (const g of groups) {
    g.items.sort((a, b) => a.createdAt.getTime() - b.createdAt.getTime())
  }

  return {
    groups,
    totalCount: groups.reduce((n, g) => n + g.items.length, 0),
    clientCount: groups.length,
  }
}

/**
 * Generates the headline text for rollup emails based on update counts.
 * Used by both the email body and the subject line to ensure they stay in sync.
 */
export function buildRollupHeadline(content: RollupEmailContent): string {
  const { groups, totalCount, clientCount } = content

  if (totalCount === 1) {
    return '1 update while you were away'
  }
  if (clientCount === 1) {
    return `${totalCount} updates on ${groups[0].clientName}`
  }
  return `${totalCount} updates across ${clientCount} clients`
}

export function buildRollupSubject(content: RollupEmailContent): string {
  const { groups, totalCount } = content

  if (totalCount === 1) {
    const g = groups[0]
    return `[Relay] ${g.clientName}: ${g.items[0].summary}`
  }
  return `[Relay] ${buildRollupHeadline(content)}`
}
