// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { config } from "dotenv";
// override:false so child processes spawned with their own DATABASE_URL
// (bootstrap, test wrappers, migrate-test-db) keep that override. .env.local
// still wins for normal local dev because the shell doesn't pre-set
// DATABASE_URL. Changed from override:true on 2026-05-15 as part of the
// Neon DB split (see projects/relay-app/2026-05-15-neon-db-split-plan.md).
config({ path: ".env.local", override: false });
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "src/db/schema.prisma",
  migrations: {
    path: "src/db/migrations",
  },
  datasource: {
    url: process.env["DATABASE_URL"],
  },
});
